ToDo/ToDo.WebUI/Areas/Admin/Controllers/PriorityController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ToDo.Business.Interfaces;
using ToDo.Entities.Concrete;
using ToDo.WebUI.Areas.Admin.Models;

namespace ToDo.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PriorityController : Controller
    {
        private readonly IPriorityService _priorityService;
        public PriorityController(IPriorityService priorityService)
        {
            _priorityService = priorityService;
        }
        public IActionResult Index()
        {
            TempData["Active"] = "priority";
            List<Priority> priorities = _priorityService.GetAll();
            List<PriorityListViewModel> model = new List<PriorityListViewModel>();
            foreach (var item in priorities)
            {
                PriorityListViewModel priorityModel = new PriorityListViewModel();
                priorityModel.Id = item.Id;
                priorityModel.Description = item.Description;
                model.Add(priorityModel);
            }
            return View(model);
        }
        public IActionResult AddPriorityTask()
        {
            TempData["Active"] = "priority";
            return View(new PriorityAddViewModel());
        }
        [HttpPost]
        public IActionResult AddPriorityTask(PriorityAddViewModel model)
        {
            
            if (ModelState.IsValid)
            {
                _priorityService.Save(new Priority
                {
                    Description = model.Description
                });
                return (RedirectToAction("Index"));
            }
            return View(model);
        }

        public IActionResult UpdatePriority(int id)
        {
            TempData["Active"] = "priority";
            var priority = _priorityService.GetWithId(id);
            PriorityUpdateViewModel model = new PriorityUpdateViewModel
            {
                Id = priority.Id,
                Description = priority.Description

            };
            return View(model);
        }
        [HttpPost]
        public IActionResult UpdatePriority(PriorityUpdateViewModel model)
        {
            if (ModelState.IsValid)
            {
                _priorityService.Update(new Priority
                {
                    Id = model.Id,
                    Description = model.Description
                });
                return RedirectToAction("Index");
            }

            return View(model);
        }



    }
}

ToDo/ToDo.WebUI/Areas/Admin/Controllers/TaskController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ToDo.Business.Interfaces;
using ToDo.Entities.Concrete;
using ToDo.WebUI.Areas.Admin.Models;

namespace ToDo.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TaskController : Controller
    {
        private readonly ITaskService _taskService;
        private readonly IPriorityService _priorityService;
        public TaskController(ITaskService taskService, IPriorityService priorityService)
        {
            _taskService = taskService;
            _priorityService = priorityService;
        }

        public IActionResult Index()
        {
            TempData["Active"] = "task";
            List<Task> tasks = _taskService.GetUncomplatedWithPriority();
            List<TaskListViewModel> model = new List<TaskListViewModel>();
            if (ModelState.IsValid)
            {

                foreach (var item in tasks)
                {
                    TaskListViewModel taskModel = new TaskListViewModel  //out of foreach
                    {
                        //Use Mapper Library
                        Id = item.Id,
                        Name = item.Name,
                        Description = item.Description,
                        DateCreated = item.DateCreated,
                        Status = item.Status,
                        Priority = item.Priority,
                        PriorityId = item.PriorityId

                    };
                    model.Add(taskModel);
                }

            }
            return View(model);
        }
        public IActionResult AddTask()
        {
            TempData["Active"] = "task";
            ViewBag.Priorities = new SelectList(_priorityService.GetAll(), "Id", "Description");

            return View(new TaskAddViewModel());
        }
        [HttpPost]
        public IActionResult AddTask(TaskAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                _taskService.Save(new Task
                {
                    Description = model.Description,
                    Name = model.Name,
                    PriorityId = model.PriorityId

                });
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult UpdateTask(int id)
        {
            TempData["Active"] = "task";
            var task = _taskService.GetWithId(id);
            TaskUpdateViewModel model = new TaskUpdateViewModel
            {
                Id = task.Id,
                Name = task.Name,
                Description = task.Description,
                PriorityId = task.PriorityId
            };
            ViewBag.Tasks = new SelectList(_priorityService.GetAll(), "Id", "Description", task.PriorityId);
            return View(model);
        }
        [HttpPost]
        public IActionResult UpdateTask(TaskUpdateViewModel model)
        {
            
            if (ModelState.IsValid)
            {
                _taskService.Update(new Task
                {
                    Id = model.Id,
                    Name=model.Name,
                    Description=model.Description,
                    PriorityId=model.PriorityId
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult DeleteTask(int id)
        {
            
            _taskService.Delete(new Task { Id = id });
            return Json(null);
        }
    }
}

ToDo/ToDo.WebUI/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@{ string active = string.Empty;
                if (TempData["Active"] != null)
                {
                    active = TempData["Active"].ToString();
                } }


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ToDO APP</title>

    <!-- Bootstrap core CSS -->

    <link href="~/lib/boostwatch/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/lib/template-css/simple-sidebar.css" rel="stylesheet" />
</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Admin Panel </div>
            <div class="list-group list-group-flush">
                <a  asp-action="Index" asp-controller="Task" class="list-group-item list-
                   group-item-action @(active=="task"?"active":"")">Task Process</a>
                <a asp-action="Index" asp-controller="Priority" class="list-group-item list-
                   group-item-action @(active=="priority"?"active":"")">Priority Process</a>
                <a href="/Admin/Priority/Index"
                   class="list-group-item list-group-item-action ">Shortcuts</a>
                <a href="#"
                   class="list-group-item list-group-item-action ">Overview</a>
                <a href="#"
                   class="list-group-item list-group-item-action ">Events</a>
                <a href="#"
                   class="list-group-item list-group-item-action ">Profile</a>
                <a href="#"
                   class="list-group-item list-group-item-action ">Status</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">Menu</button>

                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Dropdown
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </div>*@
            </nav>

            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    @RenderSection("JavaScript", false)
    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });</script>

</body>

</html>